<?php echo $this->doctype() . "\n" ?>
<html>
<head>
<?php 
    echo $this->headTitle('ZF Blog')->setSeparator(' / ')->setIndent('   ') . "\n";
    echo $this->headMeta()->setIndent('   ') . "\n"; 
    echo $this->headLink()->setIndent('   ')
         ->appendStylesheet('http://yui.yahooapis.com/2.7.0/build/reset-fonts-grids/reset-fonts-grids.css')
         ->appendStylesheet('http://yui.yahooapis.com/2.7.0/build/base/base-min.css')
         ->appendStylesheet($this->includeModifiedDate('/css/style.css')) . "\n";
    echo $this->headScript()->prependFile('http://html5shiv.googlecode.com/svn/trunk/html5.js','text/javascript',array('conditional'=>'IE')). "\n";
?>
</head>

<body>

<header id="hd" role="banner">
    <nav role="navigation">
        <?php echo $this->navigation()->menu($this->menu)->setMaxDepth(0); ?>
    </nav>
    <hgroup>
        <h1><a href="/">ZF Blog</a></h1>
        <h2>Some subheader here.</h2>
    </hgroup>
</header>

<div id="doc" class="yui-t1">


<div id="bd">
    <div id="yui-main">
        <div class="yui-b" role="main">
            <section id="content" class="yui-g">
            <?php echo $this->navigation()->breadcrumbs($this->menu); ?>
            <?php echo $this->layout()->content; ?>
            </section>
        </div>
    </div>
    <section class="yui-b">
        <nav role="navigation" aria-labelledby="leftnav-label">
            <h2 id="leftnav-label">Submenu</h2>
            <?php 
            // submenu
            echo $this->navigation()->menu($this->menu)->renderMenu(null, array(
                'minDepth' => 1,
                'maxDepth' => 1,
                'ulClass' => 'mysubmenu',
                'onlyActiveBranch' => true,
                'renderParents' => false
            )); 
            ?>
        </nav>
    </section>
    
    <section style="clear: both;">
        <?php echo $this->action('test', 'index'); ?>
    </section>


</div>

<?php echo $this->partial('_footer.phtml');  ?>

</div>


</body>
</html>
