<?php echo $this->doctype() . "\n" ?>
<html>
<head>
<?php 
    echo $this->headTitle('ZF Blog')->setSeparator(' / ')->setIndent('   ') . "\n";
    echo $this->headMeta()->setIndent('   ') . "\n"; 
    echo $this->headLink()->setIndent('   ')
         ->appendStylesheet('http://yui.yahooapis.com/2.7.0/build/reset-fonts-grids/reset-fonts-grids.css')
         ->appendStylesheet('http://yui.yahooapis.com/2.7.0/build/base/base-min.css')
         ->appendStylesheet($this->includeModifiedDate('/css/style.css')) . "\n";
    echo $this->headScript()->prependFile('http://html5shiv.googlecode.com/svn/trunk/html5.js','text/javascript',array('conditional'=>'IE')). "\n";
?>
</head>

<body>

<header id="hd" role="banner">
    <nav role="navigation" style="position: relative;">
        <?php echo $this->navigation()->menu($this->menu)->setMaxDepth(0); ?>
        <div style="font-size: 11px; position: absolute; right: 350px; top: 6px; color: #00C0FF;">
            <?php echo $this->loggedInUser(); ?>
        </div>
    </nav>
</header>

<div id="doc" class="yui-t1">
    <hgroup style="text-align: center;">
        <h1><a href="/">ZF Blog</a></h1>
        <h2>Some subheader here.</h2>
    </hgroup>

<div id="left-column">
    <section class="left-block">
        <nav role="navigation" aria-labelledby="leftnav-label">
            <h2 id="leftnav-label">Submenu</h2>
            <?php 
            // submenu
            echo $this->navigation()->menu($this->menu)->renderMenu(null, array(
                'minDepth' => 1,
                'maxDepth' => 1,
                'ulClass' => 'mysubmenu',
                'onlyActiveBranch' => true,
                'renderParents' => false
            )); 
            ?>
        </nav>
    </section>
    
    <section class="left-block">
        <?php echo $this->action('test', 'index'); ?>
    </section>
</div>

<div id="right-column">
    <div role="main">
        <section id="content" class="yui-g">
        <?php echo $this->navigation()->breadcrumbs($this->menu); ?>
        <?php echo $this->layout()->content; ?>
        </section>
    </div>
</div>

<?php echo $this->partial('_footer.phtml');  ?>

</div>


</body>
</html>
