<?php
//$url = $this->url(array('controller' => 'entry',
        //'action' => 'entryDetail', 
        //'id' => $this->id), '', true);

$url = $this->url(array('id' => $this->id), 'entry', true);
?>

<article>
    <header>
        <h2><a href="<?php echo $url; ?>">
            <?php echo $this->escape($this->title); ?></a></h2>
        <p>Posted on <time datetime="<?php echo date('Y-m-d', strtotime($this->date)); ?>">
            <?php echo date('d.m.Y, H:i', strtotime($this->date)); ?></time>
        </p>
    </header>
    <div>
        <?php echo $this->escape($this->announce); ?>
    </div>
    <footer>
        <address>By <strong><?php echo $this->escape($this->login); ?></strong></address>
        <address><?php echo count($this->testData) ? $this->escape($this->testData[0]) : ''?></address>
    </footer>
</article>
